### ISSUE TITLE
feat/mainPage - 메인페이지 구현

### ISSUE THREAD

**Issue by jeoninhwa3** [jeoninhwa3/Help-Me#17]
## Description
메인페이지 구현

## Todo
- [x] 메인페이지 ui 작업
- [x] 메인페이지 스와이퍼 컴포넌트
- [x] aos 라이브러리 적용

## up-to-date
24.09.13
