### ISSUE TITLE
feat/resultPage - 설문조사 결과 페이지

### ISSUE THREAD

**Issue by jeoninhwa3** [jeoninhwa3/Help-Me#22]
## Description
설문조사 결과 페이지

## Todo
- [x] 설문조사 결과 페이지 ui
- [x] 결과 데이터 supabase에 저장
- [x] 결과 데이터 페이지에 가져오기

## up-to-date
24.09.25-26
