### ISSUE TITLE
refactor/checkPage - 전체페이지 확인

### ISSUE THREAD

**Issue by jeoninhwa3** [jeoninhwa3/Help-Me#35]
## Description
전체페이지 확인

## Todo
- [x] 메인페이지 버튼 - 결과 페이지 연결
- [x] 설문조사, 로그인 미들웨어 잘 작동하는지 확인
- [x] 로그인, 회원가입 버튼 ui

## up-to-date
24.10.18
